---
# tasks file for adduser

#Add User
- name: add user
  user:
    name: "{{ adduser_user }}"
    shell: "{{ adduser_shell }}"
    password: "{{ adduser_password }}"
    groups: "{{ adduser_groups }}"

#Set public key in host to user
- name: set authorized key took from file
  authorized_key:
    user: "{{ adduser_user }}"
    state: present
    key: "{{ lookup('file', adduser_publickey_file) }}"
  register: add_identity_key
  when: adduser_publickey_file is defined and adduser_user is defined

# - name: Disable empty password login
#   lineinfile: dest={{ adduser_sshd_config }} regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"
#   notify: restart sshd

# - name: disable password authentication
#   lineinfile: dest={{ adduser_sshd_config }} regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
#   when: add_identity_key|success and not add_identity_key|skipped
#   notify: restart sshd

# - name: disable root account
#   lineinfile: dest={{ adduser_sshd_config }} regexp="^#?PermitRootLogin" line="PermitRootLogin no"
#   when: adduser_publickey_file is defined and adduser_user is defined
#   notify: restart sshd